id: ADAB7467B
base_file: f78A4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:35:43.067015
  last_modified_at: 2022-05-31 06:35:43.067020
