id: ADAB7467B
base_file: fD5D1.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:35:43.071456
  last_modified_at: 2022-05-31 06:35:43.071463
