id: ADAB7467B
base_file: f461F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:35:43.064821
  last_modified_at: 2022-05-31 06:35:43.064825
